// Network-first service worker: fresh files when online (updates land right
// away), cached shell when offline. Supabase API calls are never cached.
const CACHE = 'jen-island-v40';
const SHELL = ["./", "./index.html", "./css/game.css", "./manifest.webmanifest", "./assets/icon-180.png", "./assets/icon-192.png", "./assets/icon-512.png", "./assets/fonts/nunito-latin.woff2", "./assets/fonts/nunito-latin-ext.woff2", "./assets/fonts/nunito-vietnamese.woff2", "./js/core/audio.js", "./js/core/counts.js", "./js/core/haptics.js", "./js/core/input.js", "./js/core/locks.js", "./js/core/music.js", "./js/core/util.js", "./js/data/badges.js", "./js/data/changelog.js", "./js/data/game.js", "./js/data/hair.js", "./js/data/looks.js", "./js/data/lore.js", "./js/data/quests.js", "./js/data/songs.js", "./js/data/wardrobe.js", "./js/dev/flag.js", "./js/gfx/assemble.js", "./js/gfx/buildings.js", "./js/gfx/cat.js", "./js/gfx/character.js", "./js/gfx/draw.js", "./js/gfx/food.js", "./js/gfx/furniture.js", "./js/gfx/hammock.js", "./js/gfx/props.js", "./js/gfx/villager.js", "./js/guard.js", "./js/main.js", "./js/systems/ads.js", "./js/systems/album.js", "./js/systems/animals.js", "./js/systems/badges.js", "./js/systems/board.js", "./js/systems/business.js", "./js/systems/cinematic.js", "./js/systems/cloud.js", "./js/systems/crowd.js", "./js/systems/cutscene.js", "./js/systems/daily.js", "./js/systems/deeplink.js", "./js/systems/economy.js", "./js/systems/fishing.js", "./js/systems/friends.js", "./js/systems/fun.js", "./js/systems/garden.js", "./js/systems/growth.js", "./js/systems/iap.js", "./js/systems/idle.js", "./js/systems/interact.js", "./js/systems/ledger.js", "./js/systems/notify.js", "./js/systems/npc.js", "./js/systems/pets.js", "./js/systems/player.js", "./js/systems/progress.js", "./js/systems/pronouns.js", "./js/systems/rare.js", "./js/systems/restaurant.js", "./js/systems/review.js", "./js/systems/save.js", "./js/systems/scenes.js", "./js/systems/seats.js", "./js/systems/sidequests.js", "./js/systems/social.js", "./js/systems/state.js", "./js/systems/store.js", "./js/systems/story.js", "./js/systems/talk.js", "./js/systems/telemetry.js", "./js/systems/time.js", "./js/systems/tips.js", "./js/systems/vendors.js", "./js/systems/version.js", "./js/systems/weekboard.js", "./js/systems/weekly.js", "./js/ui/auth.js", "./js/ui/board.js", "./js/ui/clothes.js", "./js/ui/comfort.js", "./js/ui/conflict.js", "./js/ui/decorate.js", "./js/ui/dialogue.js", "./js/ui/hud.js", "./js/ui/lookout.js", "./js/ui/menu.js", "./js/ui/naming.js", "./js/ui/office.js", "./js/ui/petshop.js", "./js/ui/photo.js", "./js/ui/prep.js", "./js/ui/salon.js", "./js/ui/service.js", "./js/ui/sheets.js", "./js/ui/shops.js", "./js/ui/staff.js", "./js/ui/statictext.js", "./js/ui/store.js", "./js/ui/summary.js", "./js/ui/whatsnew.js", "./js/ui/worldmap.js", "./js/world/actor.js", "./js/world/interiors.js", "./js/world/island.js", "./js/world/render.js", "./js/world/scene.js"];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => e.waitUntil(Promise.all([self.clients.claim(), caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))])));
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  // always ask the server (never the phone's HTTP cache), so an update can't mix old and new files
  e.respondWith(fetch(req, { cache: 'no-cache' }).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  }).catch(() => caches.match(req).then(r => r || (req.mode === 'navigate' ? caches.match('./index.html') : Response.error()))));
});
