-- JEN Island isolated game schema inside the shared jen-simulator Supabase project.
-- Existing jen-simulator tables (such as jen_players / jen_scores) are intentionally untouched.

create table if not exists public.jen_island_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  player_name text,
  island_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jen_island_saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  save_version integer not null default 1,
  game_day integer not null default 1,
  coins bigint not null default 0,
  reputation integer not null default 0,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.jen_island_daily_summaries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_day integer not null,
  summary_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, game_day)
);

alter table public.jen_island_profiles enable row level security;
alter table public.jen_island_saves enable row level security;
alter table public.jen_island_daily_summaries enable row level security;

grant select, insert, update, delete on public.jen_island_profiles to authenticated;
grant select, insert, update, delete on public.jen_island_saves to authenticated;
grant select, insert, update, delete on public.jen_island_daily_summaries to authenticated;
grant usage, select on sequence public.jen_island_daily_summaries_id_seq to authenticated;

drop policy if exists "jen_island_profiles_select_own" on public.jen_island_profiles;
create policy "jen_island_profiles_select_own"
on public.jen_island_profiles for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_profiles_insert_own" on public.jen_island_profiles;
create policy "jen_island_profiles_insert_own"
on public.jen_island_profiles for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_profiles_update_own" on public.jen_island_profiles;
create policy "jen_island_profiles_update_own"
on public.jen_island_profiles for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_saves_select_own" on public.jen_island_saves;
create policy "jen_island_saves_select_own"
on public.jen_island_saves for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_saves_insert_own" on public.jen_island_saves;
create policy "jen_island_saves_insert_own"
on public.jen_island_saves for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_saves_update_own" on public.jen_island_saves;
create policy "jen_island_saves_update_own"
on public.jen_island_saves for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_daily_select_own" on public.jen_island_daily_summaries;
create policy "jen_island_daily_select_own"
on public.jen_island_daily_summaries for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_daily_insert_own" on public.jen_island_daily_summaries;
create policy "jen_island_daily_insert_own"
on public.jen_island_daily_summaries for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_daily_update_own" on public.jen_island_daily_summaries;
create policy "jen_island_daily_update_own"
on public.jen_island_daily_summaries for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create index if not exists jen_island_daily_summaries_user_day_idx
on public.jen_island_daily_summaries (user_id, game_day desc);
