-- JEN Island: daily save snapshots for recovery (the client keeps the latest 7 per player).
-- Isolated like every jen_island_* table; row-level security limits rows to their owner.

create table if not exists public.jen_island_save_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_day integer not null default 1,
  save_version integer not null default 1,
  save_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists jen_island_save_snapshots_user_idx on public.jen_island_save_snapshots (user_id, created_at desc);

alter table public.jen_island_save_snapshots enable row level security;
grant select, insert, delete on public.jen_island_save_snapshots to authenticated;
grant usage, select on sequence public.jen_island_save_snapshots_id_seq to authenticated;

drop policy if exists "jen_island_snapshots_select_own" on public.jen_island_save_snapshots;
create policy "jen_island_snapshots_select_own"
on public.jen_island_save_snapshots for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_snapshots_insert_own" on public.jen_island_save_snapshots;
create policy "jen_island_snapshots_insert_own"
on public.jen_island_save_snapshots for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "jen_island_snapshots_delete_own" on public.jen_island_save_snapshots;
create policy "jen_island_snapshots_delete_own"
on public.jen_island_save_snapshots for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
